const categories = ["general", "world", "nation", "business", "technology", "entertainment", "sports", "science", "health"]

const lang = new Map([
    ['Arabic', 'ar'],
    ['Chinese', 'zh'],
    ['Dutch', 'nl'],
    ['English', 'en'],
    ['French', 'fr'],
    ['German', 'de'],
    ['Greek', 'el'],
    ['Hebrew', 'he'],
    ['Hindi', 'hi'],
    ['Italian', 'it'],
    ['Japanese', 'ja'],
    ['Malayalam', 'ml'],
    ['Marathi', 'mr'],
    ['Norwegian', 'no'],
    ['Portuguese', 'pt'],
    ['Romanian', 'ro'],
    ['Russian', 'ru'],
    ['Spanish', 'es'],
    ['Swedish', 'sv'],
    ['Tamil', 'ta'],
    ['Telugu', 'te'],
    ['Ukrainian', 'uk']
])

const countries = new Map([
    ['Australia', 'au'],
    ['Brazil', 'br'],
    ['Canada', 'ca'],
    ['China', 'cn'],
    ['Egypt', 'eg'],
    ['France', 'fr'],
    ['Germany', 'de'],
    ['Greece', 'gr'],
    ["Hong Kong", 'hk'],
    ['India', 'in'],
    ['Ireland', 'ie'],
    ['Israel', 'il'],
    ['Italy', 'it'],
    ['Japan', 'jp'],
    ['Netherlands', 'nl'],
    ['Norway', 'no'],
    ['Pakistan', 'pk'],
    ['Peru', 'pe'],
    ['Philippines', 'ph'],
    ['Portugal', 'pt'],
    ['Romania', 'ro'],
    ["Russian Federation", 'ru'],
    ['Singapore', 'sg'],
    ['Spain', 'es'],
    ['Sweden', 'se'],
    ['Switzerland', 'ch'],
    ['Taiwan', 'tw'],
    ['Ukraine', 'ua'],
    ["United Kingdom", 'gb'],
    ["United States", 'us'],
])

export { categories, lang, countries }